@SchoolManager.API_HostAddress = http://localhost:5228

GET http://localhost:5228/other/hello
Accept: application/json

###
GET http://localhost:5228/other/hello
Accept: application/json

###
GET http://localhost:5228/api/student/asd/asdf
Accept: application/json


###
POST http://localhost:5228/api/student/create
Accept: application/json
Content-Type: application/json

{
 "FirstName": "joe",
 "LastName": "Does12345"
}
###
POST http://localhost:5228/api/teacher/teacher
Accept: application/json
Content-Type: application/json

{
"FirstName": "Ms joe",
"LastName": "Ms Doe",
  "qualification": "ABC"
}

###
GET http://localhost:5228/api/student/all
Accept: application/json

###
GET http://localhost:5228/api/student/1
Accept: application/json

###
GET http://localhost:5228/api/teacher/all
Accept: application/json

###
GET http://localhost:5228/api/teacher/1

Accept: application/json

###
POST http://localhost:5228/api/course/create
Accept: application/json
Content-Type: application/json

{
  "Name": "Mathematics 101",
  "Room": "A101",
  "Capacity": 30,
  "TeacherId": 2
}

###
GET http://localhost:5228/api/course/all
Accept: application/json

###
GET http://localhost:5228/api/course/1
Accept: application/json

###
POST http://localhost:5228/api/studentcoursemap/enroll?studentid=70&courseid=6
Accept: application/json
Content-Type: application/json

###
GET http://localhost:5228/api/studentcoursemap/course/1/students
Accept: application/json

###
GET http://localhost:5228/api/studentcoursemap/student/1/courses
Accept: application/json

###
POST http://localhost:5228/api/Auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
POST http://localhost:5228/api/Auth/create-user
Accept: application/json
Content-Type: application/json

{
  "username": "teacher1",
  "password": "teacher123",
  "role": 1
}

###
POST http://localhost:5228/api/Auth/set-password
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "newPassword": "123"
}

###
POST http://localhost:5228/api/Auth/update-role
Accept: application/json
Content-Type: application/json

{
  "userId": 1,
  "newRole": 0
}

